---
title: "Bioinformatics Class 12"
author: "Peng Fei Huang"
date: "5/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(bio3d)
```

# Setup HIV-Pr for docking study 

Get the protein first (i.e. download)

```{r}
file.name <- get.pdb("1hsg")
```


Read this file in and trim out the protein and small molecule ligand from everything else 
```{r}
hiv <- read.pdb(file.name)
hiv
```


```{r}
ligand <- trim.pdb(hiv, "ligand")
ligand
```

Extract protein 
```{r}
protein <- trim.pdb(hiv, "protein")
protein
```

```{r}
write.pdb(ligand, "1hsg_ligand.pdb")
write.pdb(protein, "1hsg_protein.pdb")
```


## Process docking result fro viewing in VMD

```{r}
library(bio3d)
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

#Compare our results to Merk Co. drug crystal structure 
```{r}
ori <- read.pdb("1hsg_ligand.pdbqt")
```


```{r}
rmsd(ori, res)
```

#Q6 RMSD based on nonhydrogen atoms 
```{r}
atom.select(ori, "noh")
rmsd(ori$xyz[,inds$xyz], res$xyz[, inds$xyz])
```


## Revisit Search and retrieve Adenylate kinase Structure 


```{r}
aa <- get.seq("P69441")
```

```{r}
b <- blast.pdb(aa)
```


```{r}
hits <- plot(b)
```

```{r}
head(hits$pdb.id)
```

















































